spring:
  application:
    name: gateway-secured
  redis:
    port: 6379
    host: localhost
  cloud:
    gateway:
      routes:
        - id: movies-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/movies/**
          filters:
            - RewritePath=/api/movies/(?<segment>.*), /$\{segment}
        - id: music-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/music/**
          filters:
            - RewritePath=/api/music/(?<segment>.*), /$\{segment}

server:
  port: 8080